FROM node:16-alpine as builder
# USER root
WORKDIR /usr/vue-light-bootstrap-dashboard-master
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM nginx:stable-alpine as production-stage
COPY --from=builder /usr/vue-light-bootstrap-dashboard-master/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

