version: '3.7'

services:
  front:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: admin-front
    ports:
      - 8008:8080
    restart: always
    tty: true
    volumes:
      - ./:/home/admin-front
    
  
    

